# Generated by Django 4.0.4 on 2022-05-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=70, verbose_name='Nombres')),
                ('tipoIdentificacion', models.CharField(max_length=20, verbose_name='Tipo de Identificación')),
                ('num_identificacion', models.BigIntegerField(verbose_name='Número de Identificación')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=40, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.BigIntegerField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ValorTotal', models.BigIntegerField(verbose_name='Valor Total')),
                ('tipoPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('crédito', 'Crédito')], default='Efectivo', max_length=20, verbose_name='Tipo de Pago')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.usuario', verbose_name='Usuario')),
                ('vehiculo', models.ManyToManyField(through='ventas.VehiculoVenta', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='vehiculoventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
    ]
