# Generated by Django 4.0.4 on 2022-05-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0002_vehiculoventa_venta_vehiculo_vehiculoventa_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ValorTotal',
            field=models.BigIntegerField(verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(max_length=20, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
